django_projects/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("poll/", include("polls.urls")),
]

django_projects/mysite/polls/urls.py
from django.urls import path
from .views import *
app_name="poll"
urlpatterns=[
# path('first/',index,name="index"),
# path('<int:question_id>/',detail,name="details"),

# path('<int:question_id>/results',results,name="results"),
# path('<int:question_id>/vote',vote,name="vote"),

path('first/',IndexView.as_view(),name="index"),
path('<int:pk>/',QDetailView.as_view(),name="details"),

path('<int:pk>/results',ResultsView.as_view(),name="results"),
path('<int:question_id>/vote',vote,name="vote")
]


# question_id instead of pk in the url pattern
# 

django_projects/mysite/polls/models.py
from django.db import models

# Create your models here.
class Questions(models.Model):
    text=models.CharField(max_length=50,null=True,blank=True)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return f"{self.text}"

class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self): 
        return f"{self.question.text} ->{self.choice_text}"

django_projects/mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from django.template import loader
from .models import *
from django.views.generic import *
def index(request):
    # top_five_questions=Questions.objects.all()
    top_two_questions=Questions.objects.order_by('-pub_date')[:5]  #THis will order the query result
    template=loader.get_template('polls/index.html')
    context={'latest_poll':top_two_questions}
    return HttpResponse(template.render(context,request))  

def detail(request, question_id):
    # try:
    #    question=Questions.objects.get(pk=question_id)
    # except Questions.DoesNotExist:
    #     raise Http404("404 Page not found")
    question=get_object_or_404(Questions,pk=question_id)
    context={"question":question}
    return render(request,'polls/detail.html',context)


def results(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/vote.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("poll:results", args=(question.id,)))




class IndexView(ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_poll"

    def get_queryset(self):
        """Return the last five published questions."""
        return Questions.objects.order_by("-pub_date")[:5]


class QDetailView(DetailView):
    model = Questions
    template_name = "polls/detail.html"
    context_object_name = "question"

class ResultsView(DetailView):
    model = Questions
    template_name = "polls/results.html"
    context_object_name = "question"

django_projects/mysite/polls/templates/polls/detail.html
<h1>{{ question }}</h1>
<!-- <h1>{{ question.text }}</h1> -->
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

django_projects/mysite/polls/templates/polls/index.html
{% if latest_poll %}
    <ul>
    {% for question in latest_poll %}
        <!-- <li><a href="/{{ question.id }}/">{{ question.text }}</a></li> -->
        <li><a href="{% url 'poll:details' question.id %}">{{ question.text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_projects/mysite/polls/templates/polls/results.html
<h1>{{ question.text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:vote' question.id %}">Vote again?</a>

django_projects/mysite/polls/templates/polls/vote.html
<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>